@startmindmap
*_ FILENAME.viewer
    *_ viewer.json
        *_ about
        *_ title
        *_ width
        *_ height
        *_ fullscreen
    *_ scene.json
        *_ show_grid
        *_ view_mode
        *_ background_color
        *_ selection_color
    *_ ui.json
        *_ statusbar
            *_ texts
            *_ show_fps
        *_ menubar
            *_ enable_menubar
            *_ items
                *_ text
                *_ items
                    *_ type
                    *_ text
                    *_ action
                    *_ ...
        *_ toolbar
            *_ enable_toolbar
            *_ items
                *_ type
                *_ text
                *_ action
        *_ sidebar
            *_ enable_sidebar
            *_ items
                *_ type
                *_ text
                *_ ...
        *_ sidedocks
    *_ controller.json
        *_ mouse
            *_ pan
            *_ rotate
            *_ box_selection
            *_ box_deselection
            *_ selection
            *_ multi_selection
            *_ deselection
        *_ keys
    *_ actions
    *_ geometries.json
    *_ geometry_data.json
    *_ flow.json
    *_ resources
@endmindmap
