name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_ubuntu:
    if: "!contains(github.event.pull_request.labels.*.name, 'docs-only')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]
    steps:
      - name: update
        run: sudo apt-get update
      - name: install libegl1
        run: sudo apt-get install libegl1
      - name: install python3-opengl
        run: sudo apt-get install python3-opengl
      - uses: compas-dev/compas-actions.build@v4
        with:
          invoke_lint: true
          invoke_test: true
          python: ${{ matrix.python }}

  build:
    if: "!contains(github.event.pull_request.labels.*.name, 'docs-only')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python: ["3.9", "3.10", "3.11"]

    steps:
      - uses: compas-dev/compas-actions.build@v4
        with:
          invoke_lint: true
          invoke_test: true
          python: ${{ matrix.python }}
